# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:

  webapitest:
    image: webapitest
    build:
      context: .
      dockerfile: ./UCS.WebApi/Dockerfile
    ports:
      - 5000:5000
  
  frontend:
    container_name: frontend
    image: frontend
    build: 
      context: ./UCS.Frontend
      dockerfile: Dockerfile
    volumes:
      - '/app'
      - '/app/node_modules'
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
